import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // The Claude Design canvas, imported exactly as exported (design/README.md).
    // It is the visual source material, not this project's source: linting
    // someone else's export only produces findings nobody may act on.
    "design/**",

    // Generated by `pnpm api:types` from the backend's OpenAPI document. Its
    // shape is the backend's to decide, so a rule firing here would block a
    // regeneration for a reason no edit in this repo could fix.
    "src/lib/api/schema.d.ts",
  ]),
]);

export default eslintConfig;
